### PR TITLE
Make database wrapping failsafe and propagate static config errors.

### PR DESCRIPTION
**Pull request by pkaminski**
Previously, if Fireworker._databaseWrapperCallback failed, the _cachedDatabase would remain initialized to the raw database, leaving it unwrapped.  If the failure was ignored upstream, then further calls would just use it and ignore the wrapper callback, with potentially terrible effects.  This change ensures that a failure leaves the cache unset, so future calls will try to wrap again.

Also, this change makes sure that any errors encountered during static initialization will propagate to (and invalidate) all Fireworkers. These errors invariably signal bugs in the client code so we want to make sure they're not ignored by accident.

- - -
This change is [Reviewable](https://reviewable.io/reviews/reviewable/firetruss-worker/2)

### CODE REVIEW

**Review by earlAchromatic — COMMENTED** [review]
Left a couple of questions. Code looks good to me as long as those end up being non-issues. I wanted to at least take a look at the code to get it turned around tonight but can do some more hands on testing tomorrow as well.

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/reviewable/firetruss-worker/2#-:-NCYqtbj48sJTq0ZTaXq:bkslq7s)* status: all files reviewed, 2 unresolved discussions (waiting on @pkaminski)

___
*[`src/worker.js` line 169 at r1](https://reviewable.io/reviews/reviewable/firetruss-worker/2#-NCYob5CAr297OI8C-HP:-NCYob5CAr297OI8C-HQ:b-7yxp53) ([raw file](https://github.com/reviewable/firetruss-worker/blob/7f6235cc30cb6b42ef96a7377314756dc02f57a6/src/worker.js#L169)):*
> ```JavaScript
>       this._cachedDatabase = Fireworker._databaseWrapperCallback(this._app.database());
>     } else {
>       this._cachedDatabase = this._app.database();
> ```

Are there any cases where `_databaseWrapperCallback` could be set after `_database` is accessed? This would result in the exposed db again. I am not sure I see when you would ever want to initialize it to the raw db. Doesn't our client always use a `_databaseWrapperCallback`, even if it may just return the same db?
___
*[`src/worker.js` line 184 at r1](https://reviewable.io/reviews/reviewable/firetruss-worker/2#-NCYn93o3hBGKsrc_ug0:-NCYn93o3hBGKsrc_ug1:bpwk4f2) ([raw file](https://github.com/reviewable/firetruss-worker/blob/7f6235cc30cb6b42ef96a7377314756dc02f57a6/src/worker.js#L184)):*
> ```JavaScript
>         this._app.database();
>         this._app.auth();
>         this._configError = undefined;
> ```

Do you want to keep referencing `Fireworker._staticConfigError` here or is it okay to reset it?

**Review by pkaminski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/reviewable/firetruss-worker/2)* status: all files reviewed, 1 unresolved discussion (waiting on @earlAchromatic)

___
*[`src/worker.js` line 169 at r1](https://reviewable.io/reviews/reviewable/firetruss-worker/2#-NCYob5CAr297OI8C-HP:-NCaCOKk0mUBS9t2H_X0:bscy01y) ([raw file](https://github.com/reviewable/firetruss-worker/blob/7f6235cc30cb6b42ef96a7377314756dc02f57a6/src/worker.js#L169)):*
<details><summary><i>Previously, earlAchromatic (Jacob Milhorn) wrote…</i></summary><blockquote>

Are there any cases where `_databaseWrapperCallback` could be set after `_database` is accessed? This would result in the exposed db again. I am not sure I see when you would ever want to initialize it to the raw db. Doesn't our client always use a `_databaseWrapperCallback`, even if it may just return the same db?
</blockquote></details>

That shouldn't be possible, since `_database` will only be accessed if a message comes in from the client, but receiving said message will set the `_firstMessageReceived` flag so any subsequent attempt to `setDatabaseWrapperCallback` will fail (and invalidate all Fireworkers).

I guess I could hardcode a requirement for a wrapper callback given our usage pattern, but it just feels like bad API to me...  I guess I still have this weird idea that other people might actually use this library.  ;)
___
*[`src/worker.js` line 184 at r1](https://reviewable.io/reviews/reviewable/firetruss-worker/2#-NCYn93o3hBGKsrc_ug0:-NCaDOmUAgSxMtXNglcb:bupi0iv) ([raw file](https://github.com/reviewable/firetruss-worker/blob/7f6235cc30cb6b42ef96a7377314756dc02f57a6/src/worker.js#L184)):*
<details><summary><i>Previously, earlAchromatic (Jacob Milhorn) wrote…</i></summary><blockquote>

Do you want to keep referencing `Fireworker._staticConfigError` here or is it okay to reset it?
</blockquote></details>

You're right, that's a bug that would clear the static error!  Fixed.

**Review by earlAchromatic — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/reviewable/firetruss-worker/2#-:-NCaL1-V5v_AomnByB6s:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @pkaminski)

**Comment by earlAchromatic** [comment]
*[`dist/worker.umd.js` line 200 at r2](https://reviewable.io/reviews/reviewable/firetruss-worker/2#-NCaMTfnA0PBTaX3ygwH:-NCaMTfnA0PBTaX3ygwI:b-1480zs) ([raw file](https://github.com/reviewable/firetruss-worker/blob/8f40f1aa8144ddac476e09c278dc484d5d30dcf5/dist/worker.umd.js#L200)):*
> ```JavaScript
>         this._app.database();
>         this._app.auth();
>         this._configError = undefined;
> ```

:lgtm_cancel:  Actually it looks like you need to rebuild since this (and others were not updated).

**Comment by pkaminski** [comment]
*[`dist/worker.umd.js` line 200 at r2](https://reviewable.io/reviews/reviewable/firetruss-worker/2#-NCaMTfnA0PBTaX3ygwH:-NCaN3HXEul-MXhFf0s8:bvsgp1a) ([raw file](https://github.com/reviewable/firetruss-worker/blob/8f40f1aa8144ddac476e09c278dc484d5d30dcf5/dist/worker.umd.js#L200)):*
<details><summary><i>Previously, earlAchromatic (Jacob Milhorn) wrote…</i></summary><blockquote>

:lgtm_cancel:  Actually it looks like you need to rebuild since this (and others were not updated).
</blockquote></details>

Gah, I really should normalize the infrastructure around all the extra libraries...  Some build automatically on release, others you have to remember to do it manually.  :(  I'd already merged this branch, but done on `master` and re-released as 2.4.2.

**Pull request merged**
